name: Claims Cookies Bot

on:
  workflow_dispatch:

  schedule:
    - cron: '3 2 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Firefox
        run: npx playwright install --with-deps firefox

      - name: Run getCookies.js
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: node getCookies.js
